name: Build the package

on:
  push:

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci && npm i fs fs/promises @types/fs-extra quick-mongo-super enmap discord.js events @types/events

  build:
    needs: install
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

        with:
          node-version: 16

      - name: Build the package
        run: npx -p typescript tsc && exit 0
        # run: exit 0
